package prova;
public enum Menu_Status {
	FAZER_LOGIN,
	INSC_PARTI,
	VAL_INSCRI_PARTI,
	INVA_INSCRI_PARTI,
	EMIT_CERT_PARTI,
	SUBT_ARTIGO,
	ENVIAR_AVAL_ARTIGO,
	sVER_AVAL_ARTIGO,
	ACEITAR_ARTIGO,
	REJEITAR_ARTIGO,
	LIST_ARTI_ACEI_ALFABETICA,
	LIST_ARTI_NEGA_ALFABETICA,
	VER_DADOS_ARTIGO,
	LIST_PARTIC_EVENTO_ALFABETICA,
	SAIR 
}
